
'use strict';
const hero=document.querySelector('.hero'),theme=document.querySelector('#theme-toggle'),cursor=document.querySelector('#cursor');
let dark=document.documentElement.dataset.theme!=='light',pointer={x:-9999,y:-9999},frame=0,active=true;
function apply(){window.portfolioTheme.set(dark?'dark':'light');document.body.classList.toggle('dark',dark);document.querySelector('meta[name="theme-color"]').content=dark?'#121212':'#ffffff';theme.setAttribute('aria-checked',String(dark));theme.title=dark?'Switch to light mode':'Switch to dark mode';}
function setup(){const word=document.querySelector('#last-word'),last=word.getBoundingClientRect(),hr=hero.getBoundingClientRect(),style=getComputedStyle(word);const ctx=document.createElement('canvas').getContext('2d');ctx.font=`${style.fontWeight} ${style.fontSize} ${style.fontFamily}`;const m=ctx.measureText('s');const ascent=m.actualBoundingBoxAscent,descent=m.actualBoundingBoxDescent;const fontAscent=m.fontBoundingBoxAscent||parseFloat(style.fontSize)*.8,fontDescent=m.fontBoundingBoxDescent||parseFloat(style.fontSize)*.2;const glyphHeight=ascent+descent;const height=Math.max(34,glyphHeight);theme.style.setProperty('--switch-height',height+'px');theme.style.left=(last.right-hr.left+16)+'px';theme.style.top=(last.top-hr.top+(last.height-fontAscent-fontDescent)/2+fontAscent-ascent-(height-glyphHeight)/2)+'px';}
// Each tile appears immediately, rests for 200ms, then fades over 200ms.
const hoverGrid=document.querySelector('#hover-grid'),gridContext=hoverGrid.getContext('2d');
let gridCells=[],gridWidth=0,gridHeight=0;
const revealRadius=200;
let previousHover=null;
function hash(x,y){const n=Math.sin(x*127.1+y*311.7)*43758.5453;return n-Math.floor(n);}
function noise(x,y){const a=Math.floor(x),b=Math.floor(y);let u=x-a,v=y-b;u=u*u*(3-2*u);v=v*v*(3-2*v);return hash(a,b)*(1-u)*(1-v)+hash(a+1,b)*u*(1-v)+hash(a,b+1)*(1-u)*v+hash(a+1,b+1)*u*v;}
function trailOpacity(age){const t=Math.max(0,Math.min(1,(age-200)/200));return 1-t*t*t*(t*(t*6-15)+10);}
function setupHoverGrid(){const page=document.querySelector('.page'),pr=page.getBoundingClientRect(),work=document.querySelector('#work').getBoundingClientRect(),footer=document.querySelector('footer').getBoundingClientRect();gridWidth=pr.width;gridHeight=page.offsetHeight;hoverGrid.style.height=gridHeight+'px';const dpr=Math.min(devicePixelRatio||1,2);hoverGrid.width=Math.round(gridWidth*dpr);hoverGrid.height=Math.round(gridHeight*dpr);gridContext.setTransform(dpr,0,0,dpr,0,0);gridCells=[];const regions=[[0,work.top-pr.top-10],[footer.top-pr.top,footer.bottom-pr.top]];for(const [top,bottom] of regions){for(let y=top+.5;y+4.5<bottom;y+=5){for(let x=.5;x+4.5<gridWidth;x+=5){const n=noise(x/150+7,y/170),detail=noise(x/65,y/75+8);const blend=Math.max(0,Math.min(1,(n-.24)/.52));const hue=180+blend*105;const light=29+detail*34;gridCells.push({x,y,colour:`hsl(${hue} ${48+detail*22}% ${light}%)`,lightColour:`hsl(${Math.min(hue,265)} ${48+detail*22}% ${light*1.1}%)`,texture:.48+detail*.48,warp:noise(x/160,y/160),boundary:Math.min(1,(y-top)/24,(bottom-y)/24),peak:0,seen:-10000});}}}}
function segmentDistance(x,y,a,b){const dx=b.x-a.x,dy=b.y-a.y,length=dx*dx+dy*dy;const t=length?Math.max(0,Math.min(1,((x-a.x)*dx+(y-a.y)*dy)/length)):1;return Math.hypot(x-a.x-t*dx,y-a.y-t*dy);}
function renderHoverGrid(now){gridContext.clearRect(0,0,gridWidth,gridHeight);const pr=document.querySelector('.page').getBoundingClientRect(),work=document.querySelector('#work').getBoundingClientRect(),footer=document.querySelector('footer').getBoundingClientRect();const insideX=pointer.x>=pr.left&&pointer.x<=pr.right;const region=insideX&&pointer.y>=pr.top&&pointer.y<work.top-10?'hero':insideX&&pointer.y>=footer.top&&pointer.y<=footer.bottom?'footer':null;const current={x:pointer.x-pr.left,y:pointer.y-pr.top,region};const start=previousHover&&previousHover.region===region?previousHover:current;
for(const p of gridCells){let strength=0;if(region){const d=segmentDistance(p.x+2.25,p.y+2.25,start,current);const edge=revealRadius;if(d<edge){const t=1-d/edge;strength=t*t*t*(t*(t*6-15)+10)*p.texture*p.boundary;}}
const residual=p.peak*trailOpacity(now-p.seen);if(strength>=residual&&strength>0){p.peak=strength;p.seen=now;}const alpha=Math.max(strength,residual);if(alpha<.0001)continue;gridContext.globalAlpha=alpha*.64;gridContext.fillStyle=dark?p.colour:p.lightColour;gridContext.beginPath();gridContext.roundRect(p.x,p.y,4.5,4.5,1.35);gridContext.fill();}gridContext.globalAlpha=1;previousHover=region?current:null;}
function render(){if(!active)return;renderHoverGrid(performance.now());frame=requestAnimationFrame(render);}
theme.addEventListener('click',()=>{dark=!dark;apply();});
window.addEventListener('pointermove',e=>{pointer={x:e.clientX,y:e.clientY};if(e.pointerType==='mouse'){document.body.classList.add('custom-cursor');cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px';cursor.classList.add('visible');}});
window.addEventListener('scroll',()=>{previousHover=null;},{passive:true});
function leave(){previousHover=null;pointer={x:-9999,y:-9999};cursor.classList.remove('visible');}window.addEventListener('blur',leave);window.addEventListener('pointerout',e=>{if(!e.relatedTarget)leave();});
let toastTimer;document.querySelectorAll('[data-pending]').forEach(b=>b.addEventListener('click',()=>{const t=document.querySelector('.toast');t.textContent=b.dataset.pending;t.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('visible'),3500);}));
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{setup();setupHoverGrid();},100);});document.addEventListener('visibilitychange',()=>{active=!document.hidden;if(active){cancelAnimationFrame(frame);render();}else cancelAnimationFrame(frame);});setup();setupHoverGrid();apply();render();

window.addEventListener("portfolio-theme-change",()=>{dark=document.documentElement.dataset.theme!=="light";apply();});
